In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/anime_reviews.csv")

In [3]:
## Recreating Sentiment Column
def score_to_sentiment(score):
    if score >= 8:
        return "Positive"
    elif score >= 5:
        return "Neutral"
    return "Negative"

df["sentiment"] = df["score"].apply(score_to_sentiment)

In [4]:
import nltk

nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/manaskolaskar/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/manaskolaskar/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/manaskolaskar/nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/manaskolaskar/nltk_data...

True

In [5]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    return text

In [6]:
sample = df["review_text"].iloc[0]

print("ORIGINAL:")
print(sample[:300])

print("\nCLEANED:")
print(clean_text(sample[:300]))

ORIGINAL:
Makoto Shinkai's The Garden of Words is one of those films that earns the word "immersive" without having to ask for it. From the first scene, it pulls you in — not with action, not with urgency, but with the quiet insistence of rain on glass. You settle into it before you've even decided to. The vi

CLEANED:
makoto shinkais the garden of words is one of those films that earns the word immersive without having to ask for it from the first scene it pulls you in  not with action not with urgency but with the quiet insistence of rain on glass you settle into it before youve even decided to the vi

In [10]:
## Tokenization
import nltk

print(nltk.data.path)

['/Users/manaskolaskar/nltk_data', '/Users/manaskolaskar/Developer/Projects/otaku-ai/.venv/nltk_data', '/Users/manaskolaskar/Developer/Projects/otaku-ai/.venv/share/nltk_data', '/Users/manaskolaskar/Developer/Projects/otaku-ai/.venv/lib/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data']

In [12]:
from nltk.tokenize import word_tokenize

sample_cleaned = clean_text(df["review_text"].iloc[0])

tokens = word_tokenize(sample_cleaned)

print(tokens[:50])

['makoto', 'shinkais', 'the', 'garden', 'of', 'words', 'is', 'one', 'of', 'those', 'films', 'that', 'earns', 'the', 'word', 'immersive', 'without', 'having', 'to', 'ask', 'for', 'it', 'from', 'the', 'first', 'scene', 'it', 'pulls', 'you', 'in', 'not', 'with', 'action', 'not', 'with', 'urgency', 'but', 'with', 'the', 'quiet', 'insistence', 'of', 'rain', 'on', 'glass', 'you', 'settle', 'into', 'it', 'before']

In [13]:
## StopWords Removal
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

filtered_tokens = [
    word for word in tokens
    if word not in stop_words
]

print(filtered_tokens[:50])

['makoto', 'shinkais', 'garden', 'words', 'one', 'films', 'earns', 'word', 'immersive', 'without', 'ask', 'first', 'scene', 'pulls', 'action', 'urgency', 'quiet', 'insistence', 'rain', 'glass', 'settle', 'youve', 'even', 'decided', 'visuals', 'hit', 'first', 'hit', 'hard', 'every', 'backdrop', 'wet', 'garden', 'tiles', 'light', 'fracturing', 'leaves', 'particular', 'grey', 'tokyo', 'sky', 'open', 'looks', 'less', 'like', 'animation', 'like', 'memory', 'character', 'designs']

In [14]:
## lemmatization
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

lemmatized_tokens = [
    lemmatizer.lemmatize(word)
    for word in filtered_tokens
]

print(lemmatized_tokens[:50])

['makoto', 'shinkais', 'garden', 'word', 'one', 'film', 'earns', 'word', 'immersive', 'without', 'ask', 'first', 'scene', 'pull', 'action', 'urgency', 'quiet', 'insistence', 'rain', 'glass', 'settle', 'youve', 'even', 'decided', 'visuals', 'hit', 'first', 'hit', 'hard', 'every', 'backdrop', 'wet', 'garden', 'tile', 'light', 'fracturing', 'leaf', 'particular', 'grey', 'tokyo', 'sky', 'open', 'look', 'less', 'like', 'animation', 'like', 'memory', 'character', 'design']

In [15]:
def preprocess_text(text):
    text = clean_text(text)

    tokens = word_tokenize(text)

    tokens = [
        word for word in tokens
        if word not in stop_words
    ]

    tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

    return " ".join(tokens)

In [16]:
sample = df["review_text"].iloc[0]

processed = preprocess_text(sample)

print(processed[:500])

makoto shinkais garden word one film earns word immersive without ask first scene pull action urgency quiet insistence rain glass settle youve even decided visuals hit first hit hard every backdrop wet garden tile light fracturing leaf particular grey tokyo sky open look less like animation like memory character design precise without sterile there tactile quality everyscene feeling reached screen youd come back damp finger kind craft make pause midscene sit youre looking knowing came almost fee

In [17]:
df["processed_review"] = df["review_text"].apply(preprocess_text)

In [18]:
df[["review_text", "processed_review"]].head(3)

,review_text,processed_review
0,Makoto Shinkai's The Garden of Words is one of...,makoto shinkais garden word one film earns wor...
1,Y con es termino de ver todas las peliculas de...,con e termino de ver toda la peliculas de mi d...
2,My honest opinion on K-ON!: I absolutely LOVE ...,honest opinion kon absolutely love show yui hi...

In [19]:
## TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
tfidf = TfidfVectorizer(max_features=1000)

X = tfidf.fit_transform(df["processed_review"])

In [21]:
print(type(X))
print(X.shape)

<class 'scipy.sparse._csr.csr_matrix'>
(1490, 1000)

In [22]:
feature_names = tfidf.get_feature_names_out()

print(feature_names[:50])

['ability' 'able' 'absolutely' 'academia' 'across' 'act' 'acting' 'action'
 'actor' 'actual' 'actually' 'adaptation' 'adapted' 'add' 'admit'
 'adventure' 'age' 'ago' 'ahead' 'alchemist' 'almost' 'alone' 'along'
 'alot' 'already' 'also' 'although' 'always' 'amazing' 'among' 'amount'
 'amp' 'animated' 'animation' 'anime' 'annoying' 'another' 'answer'
 'antagonist' 'anyone' 'anything' 'anyway' 'aot' 'apart' 'appeal' 'april'
 'arc' 'area' 'arent' 'armin']

In [23]:
y = df["sentiment"]

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [25]:
print(X_train.shape)
print(X_test.shape)

(1192, 1000)
(298, 1000)

In [26]:
from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()

nb_model.fit(X_train, y_train)

MultinomialNB()

In [27]:
y_pred = nb_model.predict(X_test)

print(y_pred[:10])

['Positive' 'Positive' 'Positive' 'Positive' 'Positive' 'Positive'
 'Positive' 'Positive' 'Neutral' 'Negative']

In [29]:
### Evaluation
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.6141

In [30]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    Negative       0.80      0.08      0.15        50
     Neutral       0.48      0.13      0.20        78
    Positive       0.62      0.99      0.76       170

    accuracy                           0.61       298
   macro avg       0.63      0.40      0.37       298
weighted avg       0.61      0.61      0.51       298

In [31]:
import pandas as pd

pd.Series(y_pred).value_counts()

Positive    272
Neutral      21
Negative      5
Name: count, dtype: int64

In [32]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[  4  10  36]
 [  1  10  67]
 [  0   1 169]]

In [33]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

In [34]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, y_pred_lr))

0.6375838926174496

In [35]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

    Negative       0.75      0.18      0.29        50
     Neutral       0.40      0.23      0.29        78
    Positive       0.68      0.96      0.79       170

    accuracy                           0.64       298
   macro avg       0.61      0.46      0.46       298
weighted avg       0.62      0.64      0.58       298

In [36]:
feature_names = tfidf.get_feature_names_out()

In [37]:
import pandas as pd

positive_class_idx = list(lr_model.classes_).index("Positive")

coef_df = pd.DataFrame({
    "word": feature_names,
    "weight": lr_model.coef_[positive_class_idx]
})

coef_df.sort_values("weight", ascending=False).head(20)

           word    weight
646     perfect  1.424940
34        anime  1.252884
823  steinsgate  1.187634
521        love  1.157958
750      season  1.142637
376       great  1.114947
943       voice  1.109062
28      amazing  1.072005
590      naruto  1.062224
978       world  0.957365
546         may  0.957099
827       story  0.942936
738     saitama  0.942737
455     journey  0.876438
197       demon  0.856050
751        seat  0.843936
421         hxh  0.831138
410      hooked  0.829015
238     emotion  0.800524
718   recommend  0.773686

In [38]:
negative_class_idx = list(lr_model.classes_).index("Negative")

negative_df = pd.DataFrame({
    "word": feature_names,
    "weight": lr_model.coef_[negative_class_idx]
})

negative_df.sort_values(
    "weight",
    ascending=False
).head(20)

          word    weight
474     kirito  1.307297
171      could  1.194267
365       girl  1.161292
952      waste  1.146004
104     boring  1.029219
852   supposed  1.001846
608    nothing  0.946826
289  extremely  0.926620
979      worse  0.910189
740        sao  0.877245
872   terrible  0.812223
930    useless  0.811142
760      sense  0.808404
187       deaf  0.799129
878      thing  0.779942
700      quirk  0.779371
942    visuals  0.772114
940    villain  0.753064
68         bad  0.737273
842     stupid  0.734572

In [39]:
binary_df = df.copy()

binary_df = binary_df[
    ~binary_df["score"].isin([6, 7])
]

binary_df["binary_sentiment"] = binary_df["score"].apply(
    lambda x: "Positive" if x >= 8 else "Negative"
)

binary_df["binary_sentiment"].value_counts()

binary_sentiment
Positive    849
Negative    383
Name: count, dtype: int64

In [40]:
X_binary = binary_df["processed_review"]

y_binary = binary_df["binary_sentiment"]

In [41]:
## New TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_binary = TfidfVectorizer(
    max_features=1000
)

X_binary = tfidf_binary.fit_transform(
    X_binary
)

In [42]:
from sklearn.model_selection import train_test_split

X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    X_binary,
    y_binary,
    test_size=0.2,
    random_state=42,
    stratify=y_binary
)

In [43]:
from sklearn.linear_model import LogisticRegression

lr_binary = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr_binary.fit(
    X_train_b,
    y_train_b
)

LogisticRegression(max_iter=1000, random_state=42)

In [44]:
y_pred_b = lr_binary.predict(
    X_test_b
)

In [45]:
from sklearn.metrics import (
    accuracy_score,
    classification_report
)

print(
    f"Accuracy: {accuracy_score(y_test_b, y_pred_b):.4f}"
)

print(
    classification_report(
        y_test_b,
        y_pred_b
    )
)

Accuracy: 0.7733
              precision    recall  f1-score   support

    Negative       0.86      0.32      0.47        77
    Positive       0.76      0.98      0.86       170

    accuracy                           0.77       247
   macro avg       0.81      0.65      0.66       247
weighted avg       0.79      0.77      0.74       247

In [46]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test_b,
    y_pred_b
)

print(cm)

[[ 25  52]
 [  4 166]]

In [47]:
from sklearn.linear_model import LogisticRegression

lr_balanced = LogisticRegression(
    max_iter=1000,
    random_state=42,
    class_weight="balanced"
)

lr_balanced.fit(
    X_train_b,
    y_train_b
)

y_pred_balanced = lr_balanced.predict(
    X_test_b
)

In [48]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

print(
    f"Accuracy: {accuracy_score(y_test_b, y_pred_balanced):.4f}"
)

print(
    classification_report(
        y_test_b,
        y_pred_balanced
    )
)

print(
    confusion_matrix(
        y_test_b,
        y_pred_balanced
    )
)

Accuracy: 0.8259
              precision    recall  f1-score   support

    Negative       0.69      0.81      0.74        77
    Positive       0.90      0.84      0.87       170

    accuracy                           0.83       247
   macro avg       0.80      0.82      0.81       247
weighted avg       0.84      0.83      0.83       247

[[ 62  15]
 [ 28 142]]

In [49]:
import joblib

In [50]:
joblib.dump(
    lr_balanced,
    "../artifacts/sentiment_model.pkl"
)

joblib.dump(
    tfidf_binary,
    "../artifacts/tfidf_vectorizer.pkl"
)

['../artifacts/tfidf_vectorizer.pkl']

In [51]:
import os

print(os.listdir("../artifacts"))

['tfidf_vectorizer.pkl', 'sentiment_model.pkl']

In [52]:
print(df.columns.tolist())

['review_id', 'anime_mal_id', 'anime_title', 'username', 'score', 'tags', 'review_text', 'date', 'episodes_watched', 'is_spoiler', 'is_preliminary', 'reactions_overall', 'reactions_nice', 'reactions_love_it', 'reactions_funny', 'reactions_confusing', 'reactions_informative', 'reactions_well_written', 'reactions_creative', 'sentiment', 'processed_review']

In [53]:
"binary_sentiment" in df.columns

False